# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20161004_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('passwd', models.CharField(max_length=20, null=True)),
                ('q2_1', models.TextField(null=True)),
                ('q2_2', models.TextField(null=True)),
                ('q2_3', models.TextField(null=True)),
                ('q2_4', models.TextField(null=True)),
                ('q3_1', models.TextField(null=True)),
                ('q3_2', models.TextField(null=True)),
                ('q3_3', models.TextField(null=True)),
                ('q3_4', models.TextField(null=True)),
                ('q4_1', models.TextField(null=True)),
                ('q4_2', models.TextField(null=True)),
                ('q4_3', models.TextField(null=True)),
                ('q4_4', models.TextField(null=True)),
                ('q5', models.TextField(null=True)),
                ('q6', models.TextField(null=True)),
                ('q7_1', models.IntegerField(null=True)),
                ('q7_2', models.IntegerField(null=True)),
                ('q7_3', models.IntegerField(null=True)),
                ('q7_4', models.IntegerField(null=True)),
                ('q8_1', models.IntegerField(null=True)),
                ('q8_2', models.IntegerField(null=True)),
                ('q8_3', models.IntegerField(null=True)),
                ('q8_4', models.IntegerField(null=True)),
                ('q9_1', models.IntegerField(null=True)),
                ('q9_2', models.IntegerField(null=True)),
                ('q9_3', models.IntegerField(null=True)),
                ('q9_4', models.IntegerField(null=True)),
                ('q10_1', models.IntegerField(null=True)),
                ('q10_2', models.IntegerField(null=True)),
                ('q10_3', models.IntegerField(null=True)),
                ('q10_4', models.IntegerField(null=True)),
                ('q11_1', models.IntegerField(null=True)),
                ('q11_2', models.IntegerField(null=True)),
                ('q11_3', models.IntegerField(null=True)),
                ('q11_4', models.IntegerField(null=True)),
                ('q12_1', models.IntegerField(null=True)),
                ('q12_2', models.IntegerField(null=True)),
                ('q12_3', models.IntegerField(null=True)),
                ('q12_4', models.IntegerField(null=True)),
                ('q13_1', models.IntegerField(null=True)),
                ('q13_2', models.IntegerField(null=True)),
                ('q13_3', models.IntegerField(null=True)),
                ('q13_4', models.IntegerField(null=True)),
                ('q14_1', models.IntegerField(null=True)),
                ('q14_2', models.IntegerField(null=True)),
                ('q14_3', models.IntegerField(null=True)),
                ('q14_4', models.IntegerField(null=True)),
                ('q15_1', models.IntegerField(null=True)),
                ('q15_2', models.IntegerField(null=True)),
                ('q15_3', models.IntegerField(null=True)),
                ('q15_4', models.IntegerField(null=True)),
                ('q16_1', models.IntegerField(null=True)),
                ('q16_2', models.IntegerField(null=True)),
                ('q16_3', models.IntegerField(null=True)),
                ('q16_4', models.IntegerField(null=True)),
                ('q17_1', models.IntegerField(null=True)),
                ('q17_2', models.IntegerField(null=True)),
                ('q17_3', models.IntegerField(null=True)),
                ('q17_4', models.IntegerField(null=True)),
                ('q18_1', models.IntegerField(null=True)),
                ('q18_2', models.IntegerField(null=True)),
                ('q18_3', models.IntegerField(null=True)),
                ('q18_4', models.IntegerField(null=True)),
                ('q19_1', models.IntegerField(null=True)),
                ('q19_2', models.IntegerField(null=True)),
                ('q19_3', models.IntegerField(null=True)),
                ('q19_4', models.IntegerField(null=True)),
                ('q20_1', models.IntegerField(null=True)),
                ('q20_2', models.IntegerField(null=True)),
                ('q20_3', models.IntegerField(null=True)),
                ('q20_4', models.IntegerField(null=True)),
                ('q21_1', models.IntegerField(null=True)),
                ('q21_2', models.IntegerField(null=True)),
                ('q21_3', models.IntegerField(null=True)),
                ('q21_4', models.IntegerField(null=True)),
                ('q22_1', models.IntegerField(null=True)),
                ('q22_2', models.IntegerField(null=True)),
                ('q22_3', models.IntegerField(null=True)),
                ('q22_4', models.IntegerField(null=True)),
                ('q23_1', models.IntegerField(null=True)),
                ('q23_2', models.IntegerField(null=True)),
                ('q23_3', models.IntegerField(null=True)),
                ('q23_4', models.IntegerField(null=True)),
                ('q24_1', models.IntegerField(null=True)),
                ('q24_2', models.IntegerField(null=True)),
                ('q24_3', models.IntegerField(null=True)),
                ('q24_4', models.IntegerField(null=True)),
                ('q25_1', models.IntegerField(null=True)),
                ('q25_2', models.IntegerField(null=True)),
                ('q25_3', models.IntegerField(null=True)),
                ('q25_4', models.IntegerField(null=True)),
                ('q26_1', models.IntegerField(null=True)),
                ('q26_2', models.IntegerField(null=True)),
                ('q26_3', models.IntegerField(null=True)),
                ('q26_4', models.IntegerField(null=True)),
                ('q27_1', models.IntegerField(null=True)),
                ('q27_2', models.IntegerField(null=True)),
                ('q27_3', models.IntegerField(null=True)),
                ('q27_4', models.IntegerField(null=True)),
                ('q28_1', models.IntegerField(null=True)),
                ('q28_2', models.IntegerField(null=True)),
                ('q28_3', models.IntegerField(null=True)),
                ('q28_4', models.IntegerField(null=True)),
                ('q29_1', models.IntegerField(null=True)),
                ('q29_2', models.IntegerField(null=True)),
                ('q29_3', models.IntegerField(null=True)),
                ('q29_4', models.IntegerField(null=True)),
                ('q30_1', models.IntegerField(null=True)),
                ('q30_2', models.IntegerField(null=True)),
                ('q30_3', models.IntegerField(null=True)),
                ('q30_4', models.IntegerField(null=True)),
                ('q31_1', models.IntegerField(null=True)),
                ('q31_2', models.IntegerField(null=True)),
                ('q31_3', models.IntegerField(null=True)),
                ('q31_4', models.IntegerField(null=True)),
                ('q32_1', models.IntegerField(null=True)),
                ('q32_2', models.IntegerField(null=True)),
                ('q32_3', models.IntegerField(null=True)),
                ('q32_4', models.IntegerField(null=True)),
                ('q33_1', models.IntegerField(null=True)),
                ('q33_2', models.IntegerField(null=True)),
                ('q33_3', models.IntegerField(null=True)),
                ('q33_4', models.IntegerField(null=True)),
                ('q34_1', models.IntegerField(null=True)),
                ('q34_2', models.IntegerField(null=True)),
                ('q34_3', models.IntegerField(null=True)),
                ('q34_4', models.IntegerField(null=True)),
                ('q35_1', models.IntegerField(null=True)),
                ('q35_2', models.IntegerField(null=True)),
                ('q35_3', models.IntegerField(null=True)),
                ('q35_4', models.IntegerField(null=True)),
                ('q36_1', models.IntegerField(null=True)),
                ('q36_2', models.IntegerField(null=True)),
                ('q36_3', models.IntegerField(null=True)),
                ('q36_4', models.IntegerField(null=True)),
                ('q37_1', models.IntegerField(null=True)),
                ('q37_2', models.IntegerField(null=True)),
                ('q37_3', models.IntegerField(null=True)),
                ('q37_4', models.IntegerField(null=True)),
            ],
        ),
    ]
