# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_questionnaire2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q63_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q63_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q64_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q64_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q65_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q65_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q66_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q66_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q67_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q67_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q68_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q68_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q69_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q69_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q70_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q70_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q71_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q71_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q72_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q72_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q73_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q73_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q74_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q74_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q75_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q75_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q76_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q76_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q77_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q77_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q78_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q78_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q79_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q79_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q80_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q80_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q81_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q81_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q82_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q82_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q83_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q83_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q84_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q84_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q85_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q85_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q86_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q86_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q87_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q87_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q88_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q88_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q89_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q89_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q90_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q90_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q91_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q91_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q92_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q92_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q93_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire2',
            name='q93_2',
        ),
    ]
