# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20161107_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire_exp3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('passwd', models.CharField(max_length=20, null=True)),
                ('meta2', models.DateTimeField(null=True, verbose_name=b'start_time')),
                ('meta3', models.DateTimeField(null=True, verbose_name=b'end_time')),
                ('q1_1', models.IntegerField(null=True)),
                ('q1_2', models.IntegerField(null=True)),
                ('q2_1', models.IntegerField(null=True)),
                ('q2_2', models.IntegerField(null=True)),
                ('q3_1', models.IntegerField(null=True)),
                ('q3_2', models.IntegerField(null=True)),
                ('q4_1', models.IntegerField(null=True)),
                ('q4_2', models.IntegerField(null=True)),
                ('q5_1', models.IntegerField(null=True)),
                ('q5_2', models.IntegerField(null=True)),
                ('q6_1', models.IntegerField(null=True)),
                ('q6_2', models.IntegerField(null=True)),
                ('q7_1', models.IntegerField(null=True)),
                ('q7_2', models.IntegerField(null=True)),
                ('q8_1', models.IntegerField(null=True)),
                ('q8_2', models.IntegerField(null=True)),
                ('q9_1', models.IntegerField(null=True)),
                ('q9_2', models.IntegerField(null=True)),
                ('q10_1', models.IntegerField(null=True)),
                ('q10_2', models.IntegerField(null=True)),
                ('q11_1', models.IntegerField(null=True)),
                ('q11_2', models.IntegerField(null=True)),
                ('q12_1', models.IntegerField(null=True)),
                ('q12_2', models.IntegerField(null=True)),
                ('q13_1', models.IntegerField(null=True)),
                ('q13_2', models.IntegerField(null=True)),
                ('q14_1', models.IntegerField(null=True)),
                ('q14_2', models.IntegerField(null=True)),
                ('q15_1', models.IntegerField(null=True)),
                ('q15_2', models.IntegerField(null=True)),
                ('q16_1', models.IntegerField(null=True)),
                ('q16_2', models.IntegerField(null=True)),
                ('q17_1', models.IntegerField(null=True)),
                ('q17_2', models.IntegerField(null=True)),
                ('q18_1', models.IntegerField(null=True)),
                ('q18_2', models.IntegerField(null=True)),
                ('q19_1', models.IntegerField(null=True)),
                ('q19_2', models.IntegerField(null=True)),
                ('q20_1', models.IntegerField(null=True)),
                ('q20_2', models.IntegerField(null=True)),
                ('q21_1', models.IntegerField(null=True)),
                ('q21_2', models.IntegerField(null=True)),
                ('q22_1', models.IntegerField(null=True)),
                ('q22_2', models.IntegerField(null=True)),
                ('q23_1', models.IntegerField(null=True)),
                ('q23_2', models.IntegerField(null=True)),
                ('q24_1', models.IntegerField(null=True)),
                ('q24_2', models.IntegerField(null=True)),
                ('q25_1', models.IntegerField(null=True)),
                ('q25_2', models.IntegerField(null=True)),
                ('q26_1', models.IntegerField(null=True)),
                ('q26_2', models.IntegerField(null=True)),
                ('q27_1', models.IntegerField(null=True)),
                ('q27_2', models.IntegerField(null=True)),
                ('q28_1', models.IntegerField(null=True)),
                ('q28_2', models.IntegerField(null=True)),
                ('q29_1', models.IntegerField(null=True)),
                ('q29_2', models.IntegerField(null=True)),
                ('q30_1', models.IntegerField(null=True)),
                ('q30_2', models.IntegerField(null=True)),
                ('q31_1', models.IntegerField(null=True)),
                ('q31_2', models.IntegerField(null=True)),
            ],
        ),
    ]
